### ISSUE TITLE
Таблица сторис

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/rosbank2019#16]
```
stories:
  id_stories: int
  id_user: int - создатель сториз
  id_creator: int - кто отредактировал последний
  id_images: int - ссылка на список картинок в таблице images
  
```
