### ISSUE TITLE
Таблица изображения

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/rosbank2019#17]
В таблице может быть много записей с картинками. 

```
images:
  id_stories: int
  url: text
  position: int - порядок показа картинок

```
