### ISSUE TITLE
Таблица этапов просмотра сторис

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/rosbank2019#24]
Таблица связи, какую сторис должен смотреть пользователь
```
step_action:
  id_stories: int
  id_user: int
  is_open: bool
  is_view: bool
  time: timestamp - когда появилась сторис
```
