### ISSUE TITLE
Таблица связи пользователей и функционала

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/rosbank2019#56]
Таблица обозначает, какой функционал имеется у клиента на какой платформе
```
user_features:
  id_feature: int
  id_user: int
  is_android: bool
  is_web: bool
```
