### ISSUE TITLE
Таблица статистики

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/rosbank2019#8]
храним данные о статистике использования событий пользователя
```
statistic:
  id_action: int
  id_user: int
  platform: text
```
