### ISSUE TITLE
Таблица пользователей

### ISSUE THREAD

**Issue by Txyza** [LifeLaboratory/rosbank2019#9]
```
users:
  id_user: int
  login: text
  password: text
  is_admin: bool - является ли админом
  id_profile: int - ссылка на профиль пользователя (каким функционалом пользуется)
```
